name: Build Design package

on: 
  push:
    branches:
      - main
      - next

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: ./project/design
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      discussions: write
      issues: write
      packages: write
      pages: write
      statuses: write
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: yarn

      - name: Setup Semantic Release
        run: npm install -g semantic-release@18 @semantic-release/npm @semantic-release/commit-analyzer

      - name: Release Package(s) if on default branch
        run: semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
