name: Build package

on: 
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn

      - name: Setup Semantic Release
        run: npm install -g semantic-release@18 @semantic-release/npm @semantic-release/commit-analyzer
    
      - name: Release Package(s) if on default branch
        run: semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
