name: Build package

on: 
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Testing & Linting
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install
        run: yarn

      - name: Run eslint
        run: yarn lint:eslint

      - name: Run prettier
        run: yarn lint:prettier

  publish-gpr:
    name: Publish Github Package
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      packages: write
      contents: write
    steps: 
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version-file: ".nvmrc"
          registry-url: https://npm.pkg.github.com/

      - name: Install
        run: yarn

      - name: Publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
